language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

branches:
  except:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      condition: -d ./target/doc # check that we're on stable
    script: scripts/deploy.sh
